--------------------------------------------------------
-- Archivo creado  - jueves-noviembre-27-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ATRIBUTO
--------------------------------------------------------

  CREATE TABLE "INFTEL14_5"."ATRIBUTO" 
   (	"NOMBRE" VARCHAR2(32 CHAR), 
	"Default" VARCHAR2(32 CHAR), 
	"MULTIVALUADO" VARCHAR2(32 CHAR), 
	"DERIVADO" VARCHAR2(32 CHAR), 
	"CLAVE" VARCHAR2(32 CHAR), 
	"ESQUEMA_NOMBRE" VARCHAR2(32 CHAR), 
	"TIPODATO_NOMBRE" VARCHAR2(32 CHAR), 
	"ATRIB_NOMBRE" VARCHAR2(32 CHAR), 
	"ATRIB_ESQUEMA_NOMBRE" VARCHAR2(32 CHAR), 
	"ATRIB_TIPODATO_NOMBRE" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATEGORIA
--------------------------------------------------------

  CREATE TABLE "INFTEL14_5"."CATEGORIA" 
   (	"NOMBRE" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENTIDAD
--------------------------------------------------------

  CREATE TABLE "INFTEL14_5"."ENTIDAD" 
   (	"ESQUEMA_NOMBRE" VARCHAR2(32 CHAR), 
	"TIPODATO_NOMBRE" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENTIDADDEBIL
--------------------------------------------------------

  CREATE TABLE "INFTEL14_5"."ENTIDADDEBIL" 
   (	"ESQUEMA_NOMBRE" VARCHAR2(32 CHAR), 
	"TIPODATO_NOMBRE" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESPECIALIZACION
--------------------------------------------------------

  CREATE TABLE "INFTEL14_5"."ESPECIALIZACION" 
   (	"NOMBRE" VARCHAR2(32 CHAR), 
	"DISJUNTA" VARCHAR2(1 CHAR), 
	"TOTAL" VARCHAR2(1 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESQUEMA
--------------------------------------------------------

  CREATE TABLE "INFTEL14_5"."ESQUEMA" 
   (	"NOMBRE" VARCHAR2(32 CHAR), 
	"AUTOR" VARCHAR2(32 CHAR), 
	"VERSION" VARCHAR2(32 CHAR), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RELACION
--------------------------------------------------------

  CREATE TABLE "INFTEL14_5"."RELACION" 
   (	"ESQUEMA_NOMBRE" VARCHAR2(32 CHAR), 
	"TIPODATO_NOMBRE" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RELACIONIDENTIFICACIÓN
--------------------------------------------------------

  CREATE TABLE "INFTEL14_5"."RELACIONIDENTIFICACIÓN" 
   (	"R_ESQUEMA_NOMBRE" VARCHAR2(32 CHAR), 
	"R_TIPODATO_NOMBRE" VARCHAR2(32 CHAR), 
	"ED_ESQUEMA_NOMBRE" VARCHAR2(32 CHAR), 
	"ED_TIPODATO_NOMBRE" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SE_RELACIONA
--------------------------------------------------------

  CREATE TABLE "INFTEL14_5"."SE_RELACIONA" 
   (	"E_ESQUEMA_NOMBRE" VARCHAR2(32 CHAR), 
	"E_TIPODATO_NOMBRE" VARCHAR2(32 CHAR), 
	"R_ESQUEMA_NOMBRE" VARCHAR2(32 CHAR), 
	"R_TIPODATO_NOMBRE" VARCHAR2(32 CHAR), 
	"FUNCIÓN" VARCHAR2(32 BYTE), 
	"CAD_MIN" VARCHAR2(2 CHAR), 
	"CAD_MAX" VARCHAR2(2 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUBCLASE_CAT
--------------------------------------------------------

  CREATE TABLE "INFTEL14_5"."SUBCLASE_CAT" 
   (	"CATEGORIA_NOMBRE" VARCHAR2(32 CHAR), 
	"ESQUEMA_NOMBRE" VARCHAR2(32 CHAR), 
	"TIPODATO_NOMBRE" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUBCLASE_ESP
--------------------------------------------------------

  CREATE TABLE "INFTEL14_5"."SUBCLASE_ESP" 
   (	"ESPECIALIZACION_NOMBRE" VARCHAR2(32 CHAR), 
	"ESQUEMA_NOMBRE" VARCHAR2(32 CHAR), 
	"TIPODATO_NOMBRE" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUPERCLASE_CAT
--------------------------------------------------------

  CREATE TABLE "INFTEL14_5"."SUPERCLASE_CAT" 
   (	"CATEGORIA_NOMBRE" VARCHAR2(32 CHAR), 
	"ESQUEMA_NOMBRE" VARCHAR2(32 CHAR), 
	"TIPODATO_NOMBRE" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUPERCLASE_ESP
--------------------------------------------------------

  CREATE TABLE "INFTEL14_5"."SUPERCLASE_ESP" 
   (	"ESPECIALIZACION_NOMBRE" VARCHAR2(32 CHAR), 
	"ESQUEMA_NOMBRE" VARCHAR2(32 CHAR), 
	"TIPODATO_NOMBRE" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPODATO
--------------------------------------------------------

  CREATE TABLE "INFTEL14_5"."TIPODATO" 
   (	"NOMBRE" VARCHAR2(32 CHAR), 
	"ESQUEMA_NOMBRE" VARCHAR2(32 CHAR), 
	"DISCRIMINADOR" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into INFTEL14_5.ATRIBUTO
SET DEFINE OFF;
Insert into INFTEL14_5.ATRIBUTO (NOMBRE,"Default",MULTIVALUADO,DERIVADO,CLAVE,ESQUEMA_NOMBRE,TIPODATO_NOMBRE,ATRIB_NOMBRE,ATRIB_ESQUEMA_NOMBRE,ATRIB_TIPODATO_NOMBRE) values ('Nombre',null,null,null,'1','Esquema','Esquema',null,null,null);
Insert into INFTEL14_5.ATRIBUTO (NOMBRE,"Default",MULTIVALUADO,DERIVADO,CLAVE,ESQUEMA_NOMBRE,TIPODATO_NOMBRE,ATRIB_NOMBRE,ATRIB_ESQUEMA_NOMBRE,ATRIB_TIPODATO_NOMBRE) values ('Autor',null,null,null,'0','Esquema','Esquema',null,null,null);
Insert into INFTEL14_5.ATRIBUTO (NOMBRE,"Default",MULTIVALUADO,DERIVADO,CLAVE,ESQUEMA_NOMBRE,TIPODATO_NOMBRE,ATRIB_NOMBRE,ATRIB_ESQUEMA_NOMBRE,ATRIB_TIPODATO_NOMBRE) values ('Version',null,null,null,'0','Esquema','Esquema',null,null,null);
Insert into INFTEL14_5.ATRIBUTO (NOMBRE,"Default",MULTIVALUADO,DERIVADO,CLAVE,ESQUEMA_NOMBRE,TIPODATO_NOMBRE,ATRIB_NOMBRE,ATRIB_ESQUEMA_NOMBRE,ATRIB_TIPODATO_NOMBRE) values ('Fecha',null,null,null,'0','Esquema','Esquema',null,null,null);
Insert into INFTEL14_5.ATRIBUTO (NOMBRE,"Default",MULTIVALUADO,DERIVADO,CLAVE,ESQUEMA_NOMBRE,TIPODATO_NOMBRE,ATRIB_NOMBRE,ATRIB_ESQUEMA_NOMBRE,ATRIB_TIPODATO_NOMBRE) values ('Nombre',null,null,null,'1','Esquema','TipoDato',null,null,null);
Insert into INFTEL14_5.ATRIBUTO (NOMBRE,"Default",MULTIVALUADO,DERIVADO,CLAVE,ESQUEMA_NOMBRE,TIPODATO_NOMBRE,ATRIB_NOMBRE,ATRIB_ESQUEMA_NOMBRE,ATRIB_TIPODATO_NOMBRE) values ('Nombre',null,null,null,'1','Esquema','Atributo',null,null,null);
Insert into INFTEL14_5.ATRIBUTO (NOMBRE,"Default",MULTIVALUADO,DERIVADO,CLAVE,ESQUEMA_NOMBRE,TIPODATO_NOMBRE,ATRIB_NOMBRE,ATRIB_ESQUEMA_NOMBRE,ATRIB_TIPODATO_NOMBRE) values ('Default',null,null,null,'0','Esquema','Atributo',null,null,null);
Insert into INFTEL14_5.ATRIBUTO (NOMBRE,"Default",MULTIVALUADO,DERIVADO,CLAVE,ESQUEMA_NOMBRE,TIPODATO_NOMBRE,ATRIB_NOMBRE,ATRIB_ESQUEMA_NOMBRE,ATRIB_TIPODATO_NOMBRE) values ('Multivaluado',null,null,null,'0','Esquema','Atributo',null,null,null);
Insert into INFTEL14_5.ATRIBUTO (NOMBRE,"Default",MULTIVALUADO,DERIVADO,CLAVE,ESQUEMA_NOMBRE,TIPODATO_NOMBRE,ATRIB_NOMBRE,ATRIB_ESQUEMA_NOMBRE,ATRIB_TIPODATO_NOMBRE) values ('Clave',null,null,null,'0','Esquema','Atributo',null,null,null);
Insert into INFTEL14_5.ATRIBUTO (NOMBRE,"Default",MULTIVALUADO,DERIVADO,CLAVE,ESQUEMA_NOMBRE,TIPODATO_NOMBRE,ATRIB_NOMBRE,ATRIB_ESQUEMA_NOMBRE,ATRIB_TIPODATO_NOMBRE) values ('Derivado',null,null,null,'0','Esquema','Atributo',null,null,null);
Insert into INFTEL14_5.ATRIBUTO (NOMBRE,"Default",MULTIVALUADO,DERIVADO,CLAVE,ESQUEMA_NOMBRE,TIPODATO_NOMBRE,ATRIB_NOMBRE,ATRIB_ESQUEMA_NOMBRE,ATRIB_TIPODATO_NOMBRE) values ('Nombre',null,null,null,'1','Esquema','Categoria',null,null,null);
Insert into INFTEL14_5.ATRIBUTO (NOMBRE,"Default",MULTIVALUADO,DERIVADO,CLAVE,ESQUEMA_NOMBRE,TIPODATO_NOMBRE,ATRIB_NOMBRE,ATRIB_ESQUEMA_NOMBRE,ATRIB_TIPODATO_NOMBRE) values ('Nombre',null,null,null,'1','Esquema','Especializacion',null,null,null);
Insert into INFTEL14_5.ATRIBUTO (NOMBRE,"Default",MULTIVALUADO,DERIVADO,CLAVE,ESQUEMA_NOMBRE,TIPODATO_NOMBRE,ATRIB_NOMBRE,ATRIB_ESQUEMA_NOMBRE,ATRIB_TIPODATO_NOMBRE) values ('Disjunta',null,null,null,'0','Esquema','Especializacion',null,null,null);
Insert into INFTEL14_5.ATRIBUTO (NOMBRE,"Default",MULTIVALUADO,DERIVADO,CLAVE,ESQUEMA_NOMBRE,TIPODATO_NOMBRE,ATRIB_NOMBRE,ATRIB_ESQUEMA_NOMBRE,ATRIB_TIPODATO_NOMBRE) values ('Total',null,null,null,'0','Esquema','Especializacion',null,null,null);
Insert into INFTEL14_5.ATRIBUTO (NOMBRE,"Default",MULTIVALUADO,DERIVADO,CLAVE,ESQUEMA_NOMBRE,TIPODATO_NOMBRE,ATRIB_NOMBRE,ATRIB_ESQUEMA_NOMBRE,ATRIB_TIPODATO_NOMBRE) values ('Funcion',null,null,null,'0','Esquema','Relaciona',null,null,null);
Insert into INFTEL14_5.ATRIBUTO (NOMBRE,"Default",MULTIVALUADO,DERIVADO,CLAVE,ESQUEMA_NOMBRE,TIPODATO_NOMBRE,ATRIB_NOMBRE,ATRIB_ESQUEMA_NOMBRE,ATRIB_TIPODATO_NOMBRE) values ('Cad_Min',null,null,null,'0','Esquema','Relaciona',null,null,null);
Insert into INFTEL14_5.ATRIBUTO (NOMBRE,"Default",MULTIVALUADO,DERIVADO,CLAVE,ESQUEMA_NOMBRE,TIPODATO_NOMBRE,ATRIB_NOMBRE,ATRIB_ESQUEMA_NOMBRE,ATRIB_TIPODATO_NOMBRE) values ('Cad_Max',null,null,null,'0','Esquema','Relaciona',null,null,null);
Insert into INFTEL14_5.ATRIBUTO (NOMBRE,"Default",MULTIVALUADO,DERIVADO,CLAVE,ESQUEMA_NOMBRE,TIPODATO_NOMBRE,ATRIB_NOMBRE,ATRIB_ESQUEMA_NOMBRE,ATRIB_TIPODATO_NOMBRE) values ('Discriminador',null,null,null,'0','Esquema','TipoDato',null,null,null);
REM INSERTING into INFTEL14_5.CATEGORIA
SET DEFINE OFF;
REM INSERTING into INFTEL14_5.ENTIDAD
SET DEFINE OFF;
Insert into INFTEL14_5.ENTIDAD (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','Atributo');
Insert into INFTEL14_5.ENTIDAD (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','Categoria');
Insert into INFTEL14_5.ENTIDAD (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','Entidad');
Insert into INFTEL14_5.ENTIDAD (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','EntidadDebil');
Insert into INFTEL14_5.ENTIDAD (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','Especializacion');
Insert into INFTEL14_5.ENTIDAD (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','Esquema');
Insert into INFTEL14_5.ENTIDAD (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','Relacion');
Insert into INFTEL14_5.ENTIDAD (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','RelacionIdentificacion');
Insert into INFTEL14_5.ENTIDAD (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','TipoDato');
REM INSERTING into INFTEL14_5.ENTIDADDEBIL
SET DEFINE OFF;
Insert into INFTEL14_5.ENTIDADDEBIL (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','Atributo');
Insert into INFTEL14_5.ENTIDADDEBIL (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','EntidadDebil');
Insert into INFTEL14_5.ENTIDADDEBIL (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','RelacionIdentificacion');
Insert into INFTEL14_5.ENTIDADDEBIL (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','TipoDato');
REM INSERTING into INFTEL14_5.ESPECIALIZACION
SET DEFINE OFF;
Insert into INFTEL14_5.ESPECIALIZACION (NOMBRE,DISJUNTA,TOTAL) values ('EntRel','1','1');
REM INSERTING into INFTEL14_5.ESQUEMA
SET DEFINE OFF;
Insert into INFTEL14_5.ESQUEMA (NOMBRE,AUTOR,VERSION,FECHA) values ('Esquema','Christian','1.0',to_date('26/11/14','DD/MM/RR'));
REM INSERTING into INFTEL14_5.RELACION
SET DEFINE OFF;
Insert into INFTEL14_5.RELACION (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','Compuesto');
Insert into INFTEL14_5.RELACION (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','Contiene');
Insert into INFTEL14_5.RELACION (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','Identifica');
Insert into INFTEL14_5.RELACION (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','RelDebil');
Insert into INFTEL14_5.RELACION (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','RelEnt');
Insert into INFTEL14_5.RELACION (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','RelIdent');
Insert into INFTEL14_5.RELACION (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','RelRel');
Insert into INFTEL14_5.RELACION (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','Relaciona');
Insert into INFTEL14_5.RELACION (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','SubClase Cat');
Insert into INFTEL14_5.RELACION (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','SubClase Esp');
Insert into INFTEL14_5.RELACION (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','SuperClase Cat');
Insert into INFTEL14_5.RELACION (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','SuperClase Esp');
Insert into INFTEL14_5.RELACION (ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('Esquema','Tiene');
REM INSERTING into INFTEL14_5.RELACIONIDENTIFICACIÓN
SET DEFINE OFF;
Insert into INFTEL14_5.RELACIONIDENTIFICACIÓN (R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,ED_ESQUEMA_NOMBRE,ED_TIPODATO_NOMBRE) values ('Esquema','Contiene','Esquema','TipoDato');
Insert into INFTEL14_5.RELACIONIDENTIFICACIÓN (R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,ED_ESQUEMA_NOMBRE,ED_TIPODATO_NOMBRE) values ('Esquema','RelDebil','Esquema','EntidadDebil');
Insert into INFTEL14_5.RELACIONIDENTIFICACIÓN (R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,ED_ESQUEMA_NOMBRE,ED_TIPODATO_NOMBRE) values ('Esquema','RelIdent','Esquema','RelacionIdentificacion');
Insert into INFTEL14_5.RELACIONIDENTIFICACIÓN (R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,ED_ESQUEMA_NOMBRE,ED_TIPODATO_NOMBRE) values ('Esquema','Tiene','Esquema','Atributo');
REM INSERTING into INFTEL14_5.SE_RELACIONA
SET DEFINE OFF;
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','Esquema','Esquema','Contiene','Contienen','0','N');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','TipoDato','Esquema','Contiene','Es contenido','1','1');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','TipoDato','Esquema','Tiene','Tienen','0','N');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','Atributo','Esquema','Tiene','Pertenece','1','1');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','Atributo','Esquema','Compuesto','Compone','0','N');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','Atributo','Esquema','Compuesto','Se Componen','1','1');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','TipoDato','Esquema','RelEnt','Son','1','1');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','TipoDato','Esquema','RelRel','Son','1','1');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','Entidad','Esquema','RelEnt','Proviene','1','1');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','Relacion','Esquema','RelRel','Proviene','1','1');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','Entidad','Esquema','SuperClase Esp','Pertenece','0','N');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','Entidad','Esquema','SubClase Esp','Pertenece','0','N');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','Especializacion','Esquema','SuperClase Esp','Integra','0','N');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','Especializacion','Esquema','SubClase Esp','Integra','0','N');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','Entidad','Esquema','SuperClase Cat','Pertenece','0','N');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','Entidad','Esquema','SubClase Cat','Pertenece','0','N');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','Categoria','Esquema','SuperClase Cat','Integra','2','N');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','Categoria','Esquema','SubClase Cat','Integra','0','N');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','Entidad','Esquema','RelDebil','Deriva','0','N');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','EntidadDebil','Esquema','Identifica','Identifica','1','1');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','Relacion','Esquema','RelIdent','Deriva','0','N');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','RelacionIdentificacion','Esquema','Identifica','Identifica','1','1');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','EntidadDebil','Esquema','RelDebil','Provienen','1','1');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','RelacionIdentificacion','Esquema','RelIdent','Provienen','1','1');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','Entidad','Esquema','Relaciona','Se Relacionan','0','N');
Insert into INFTEL14_5.SE_RELACIONA (E_ESQUEMA_NOMBRE,E_TIPODATO_NOMBRE,R_ESQUEMA_NOMBRE,R_TIPODATO_NOMBRE,FUNCIÓN,CAD_MIN,CAD_MAX) values ('Esquema','Relacion','Esquema','Relaciona','Unen','1','N');
REM INSERTING into INFTEL14_5.SUBCLASE_CAT
SET DEFINE OFF;
REM INSERTING into INFTEL14_5.SUBCLASE_ESP
SET DEFINE OFF;
Insert into INFTEL14_5.SUBCLASE_ESP (ESPECIALIZACION_NOMBRE,ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('EntRel','Esquema','Entidad');
Insert into INFTEL14_5.SUBCLASE_ESP (ESPECIALIZACION_NOMBRE,ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('EntRel','Esquema','Relacion');
REM INSERTING into INFTEL14_5.SUPERCLASE_CAT
SET DEFINE OFF;
REM INSERTING into INFTEL14_5.SUPERCLASE_ESP
SET DEFINE OFF;
Insert into INFTEL14_5.SUPERCLASE_ESP (ESPECIALIZACION_NOMBRE,ESQUEMA_NOMBRE,TIPODATO_NOMBRE) values ('EntRel','Esquema','TipoDato');
REM INSERTING into INFTEL14_5.TIPODATO
SET DEFINE OFF;
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('RelDebil','Esquema','1');
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('RelIdent','Esquema','1');
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('RelEnt','Esquema','1');
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('RelRel','Esquema','1');
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('Esquema','Esquema','0');
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('Contiene','Esquema','1');
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('TipoDato','Esquema','0');
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('Tiene','Esquema','1');
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('Atributo','Esquema','0');
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('Compuesto','Esquema','1');
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('Entidad','Esquema','0');
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('Relacion','Esquema','0');
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('SuperClase Esp','Esquema','1');
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('SubClase Esp','Esquema','1');
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('SuperClase Cat','Esquema','1');
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('SubClase Cat','Esquema','1');
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('Especializacion','Esquema','0');
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('Categoria','Esquema','0');
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('EntidadDebil','Esquema','0');
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('Identifica','Esquema','1');
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('RelacionIdentificacion','Esquema','0');
Insert into INFTEL14_5.TIPODATO (NOMBRE,ESQUEMA_NOMBRE,DISCRIMINADOR) values ('Relaciona','Esquema','1');
--------------------------------------------------------
--  DDL for Index SUPERCLASE_ESP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INFTEL14_5"."SUPERCLASE_ESP_PK" ON "INFTEL14_5"."SUPERCLASE_ESP" ("ESPECIALIZACION_NOMBRE", "ESQUEMA_NOMBRE", "TIPODATO_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ESQUEMA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INFTEL14_5"."ESQUEMA_PK" ON "INFTEL14_5"."ESQUEMA" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ENTIDADIDENTIFICACIÓN__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "INFTEL14_5"."ENTIDADIDENTIFICACIÓN__IDX" ON "INFTEL14_5"."RELACIONIDENTIFICACIÓN" ("ED_ESQUEMA_NOMBRE", "ED_TIPODATO_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CATEGORIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INFTEL14_5"."CATEGORIA_PK" ON "INFTEL14_5"."CATEGORIA" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RELACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INFTEL14_5"."RELACION_PK" ON "INFTEL14_5"."RELACION" ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUBCLASE_ESP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INFTEL14_5"."SUBCLASE_ESP_PK" ON "INFTEL14_5"."SUBCLASE_ESP" ("ESPECIALIZACION_NOMBRE", "ESQUEMA_NOMBRE", "TIPODATO_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ENTIDAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INFTEL14_5"."ENTIDAD_PK" ON "INFTEL14_5"."ENTIDAD" ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ENTIDADDEBIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INFTEL14_5"."ENTIDADDEBIL_PK" ON "INFTEL14_5"."ENTIDADDEBIL" ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ATRIBUTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INFTEL14_5"."ATRIBUTO_PK" ON "INFTEL14_5"."ATRIBUTO" ("NOMBRE", "ESQUEMA_NOMBRE", "TIPODATO_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TIPODATO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INFTEL14_5"."TIPODATO_PK" ON "INFTEL14_5"."TIPODATO" ("ESQUEMA_NOMBRE", "NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SE_RELACIONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INFTEL14_5"."SE_RELACIONA_PK" ON "INFTEL14_5"."SE_RELACIONA" ("E_ESQUEMA_NOMBRE", "E_TIPODATO_NOMBRE", "R_ESQUEMA_NOMBRE", "R_TIPODATO_NOMBRE", "FUNCIÓN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ESPECIALIZACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INFTEL14_5"."ESPECIALIZACION_PK" ON "INFTEL14_5"."ESPECIALIZACION" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUPERCLASE_CAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INFTEL14_5"."SUPERCLASE_CAT_PK" ON "INFTEL14_5"."SUPERCLASE_CAT" ("CATEGORIA_NOMBRE", "ESQUEMA_NOMBRE", "TIPODATO_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RELACIONIDENTIFICACIÓN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INFTEL14_5"."RELACIONIDENTIFICACIÓN_PK" ON "INFTEL14_5"."RELACIONIDENTIFICACIÓN" ("R_ESQUEMA_NOMBRE", "R_TIPODATO_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUBCLASE_CAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INFTEL14_5"."SUBCLASE_CAT_PK" ON "INFTEL14_5"."SUBCLASE_CAT" ("CATEGORIA_NOMBRE", "ESQUEMA_NOMBRE", "TIPODATO_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ENTIDADDEBIL
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."ENTIDADDEBIL" ADD CONSTRAINT "ENTIDADDEBIL_PK" PRIMARY KEY ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "INFTEL14_5"."ENTIDADDEBIL" MODIFY ("ESQUEMA_NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."ENTIDADDEBIL" MODIFY ("TIPODATO_NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORIA
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."CATEGORIA" ADD CONSTRAINT "CATEGORIA_PK" PRIMARY KEY ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "INFTEL14_5"."CATEGORIA" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENTIDAD
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."ENTIDAD" ADD CONSTRAINT "ENTIDAD_PK" PRIMARY KEY ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "INFTEL14_5"."ENTIDAD" MODIFY ("ESQUEMA_NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."ENTIDAD" MODIFY ("TIPODATO_NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUPERCLASE_ESP
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."SUPERCLASE_ESP" ADD CONSTRAINT "SUPERCLASE_ESP_PK" PRIMARY KEY ("ESPECIALIZACION_NOMBRE", "ESQUEMA_NOMBRE", "TIPODATO_NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "INFTEL14_5"."SUPERCLASE_ESP" MODIFY ("ESPECIALIZACION_NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."SUPERCLASE_ESP" MODIFY ("ESQUEMA_NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."SUPERCLASE_ESP" MODIFY ("TIPODATO_NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESQUEMA
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."ESQUEMA" ADD CONSTRAINT "ESQUEMA_PK" PRIMARY KEY ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "INFTEL14_5"."ESQUEMA" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."ESQUEMA" MODIFY ("FECHA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUBCLASE_CAT
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."SUBCLASE_CAT" ADD CONSTRAINT "SUBCLASE_CAT_PK" PRIMARY KEY ("CATEGORIA_NOMBRE", "ESQUEMA_NOMBRE", "TIPODATO_NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "INFTEL14_5"."SUBCLASE_CAT" MODIFY ("CATEGORIA_NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."SUBCLASE_CAT" MODIFY ("ESQUEMA_NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."SUBCLASE_CAT" MODIFY ("TIPODATO_NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUPERCLASE_CAT
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."SUPERCLASE_CAT" ADD CONSTRAINT "SUPERCLASE_CAT_PK" PRIMARY KEY ("CATEGORIA_NOMBRE", "ESQUEMA_NOMBRE", "TIPODATO_NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "INFTEL14_5"."SUPERCLASE_CAT" MODIFY ("CATEGORIA_NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."SUPERCLASE_CAT" MODIFY ("ESQUEMA_NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."SUPERCLASE_CAT" MODIFY ("TIPODATO_NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SE_RELACIONA
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."SE_RELACIONA" ADD CONSTRAINT "SE_RELACIONA_PK" PRIMARY KEY ("E_ESQUEMA_NOMBRE", "E_TIPODATO_NOMBRE", "R_ESQUEMA_NOMBRE", "R_TIPODATO_NOMBRE", "FUNCIÓN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "INFTEL14_5"."SE_RELACIONA" MODIFY ("E_ESQUEMA_NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."SE_RELACIONA" MODIFY ("E_TIPODATO_NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."SE_RELACIONA" MODIFY ("R_ESQUEMA_NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."SE_RELACIONA" MODIFY ("R_TIPODATO_NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."SE_RELACIONA" MODIFY ("FUNCIÓN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RELACIONIDENTIFICACIÓN
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."RELACIONIDENTIFICACIÓN" ADD CONSTRAINT "RELACIONIDENTIFICACIÓN_PK" PRIMARY KEY ("R_ESQUEMA_NOMBRE", "R_TIPODATO_NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "INFTEL14_5"."RELACIONIDENTIFICACIÓN" MODIFY ("R_ESQUEMA_NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."RELACIONIDENTIFICACIÓN" MODIFY ("R_TIPODATO_NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."RELACIONIDENTIFICACIÓN" MODIFY ("ED_ESQUEMA_NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."RELACIONIDENTIFICACIÓN" MODIFY ("ED_TIPODATO_NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATRIBUTO
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."ATRIBUTO" ADD CONSTRAINT "ATRIBUTO_PK" PRIMARY KEY ("NOMBRE", "ESQUEMA_NOMBRE", "TIPODATO_NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "INFTEL14_5"."ATRIBUTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."ATRIBUTO" MODIFY ("ESQUEMA_NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."ATRIBUTO" MODIFY ("TIPODATO_NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUBCLASE_ESP
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."SUBCLASE_ESP" ADD CONSTRAINT "SUBCLASE_ESP_PK" PRIMARY KEY ("ESPECIALIZACION_NOMBRE", "ESQUEMA_NOMBRE", "TIPODATO_NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "INFTEL14_5"."SUBCLASE_ESP" MODIFY ("ESPECIALIZACION_NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."SUBCLASE_ESP" MODIFY ("ESQUEMA_NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."SUBCLASE_ESP" MODIFY ("TIPODATO_NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RELACION
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."RELACION" ADD CONSTRAINT "RELACION_PK" PRIMARY KEY ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "INFTEL14_5"."RELACION" MODIFY ("ESQUEMA_NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."RELACION" MODIFY ("TIPODATO_NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPODATO
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."TIPODATO" ADD CONSTRAINT "FKARC_1_LOV" CHECK ( Discriminador IN ( '0', '1' ) ) ENABLE;
 
  ALTER TABLE "INFTEL14_5"."TIPODATO" ADD CONSTRAINT "FKARC_1_NN" CHECK ( Discriminador IS NOT NULL ) ENABLE;
 
  ALTER TABLE "INFTEL14_5"."TIPODATO" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."TIPODATO" MODIFY ("ESQUEMA_NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "INFTEL14_5"."TIPODATO" ADD CONSTRAINT "TIPODATO_PK" PRIMARY KEY ("ESQUEMA_NOMBRE", "NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESPECIALIZACION
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."ESPECIALIZACION" ADD CONSTRAINT "ESPECIALIZACION_PK" PRIMARY KEY ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "INFTEL14_5"."ESPECIALIZACION" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ATRIBUTO
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."ATRIBUTO" ADD CONSTRAINT "ATRIBUTO_ATRIBUTO_FK" FOREIGN KEY ("ATRIB_NOMBRE", "ATRIB_ESQUEMA_NOMBRE", "ATRIB_TIPODATO_NOMBRE")
	  REFERENCES "INFTEL14_5"."ATRIBUTO" ("NOMBRE", "ESQUEMA_NOMBRE", "TIPODATO_NOMBRE") ENABLE;
 
  ALTER TABLE "INFTEL14_5"."ATRIBUTO" ADD CONSTRAINT "ATRIBUTO_TIPODATO_FK" FOREIGN KEY ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE")
	  REFERENCES "INFTEL14_5"."TIPODATO" ("ESQUEMA_NOMBRE", "NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENTIDAD
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."ENTIDAD" ADD CONSTRAINT "ENTIDAD_TIPODATO_FK" FOREIGN KEY ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE")
	  REFERENCES "INFTEL14_5"."TIPODATO" ("ESQUEMA_NOMBRE", "NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENTIDADDEBIL
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."ENTIDADDEBIL" ADD CONSTRAINT "ENTIDADDEBIL_ENTIDAD_FK" FOREIGN KEY ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE")
	  REFERENCES "INFTEL14_5"."ENTIDAD" ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RELACION
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."RELACION" ADD CONSTRAINT "RELACION_TIPODATO_FK" FOREIGN KEY ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE")
	  REFERENCES "INFTEL14_5"."TIPODATO" ("ESQUEMA_NOMBRE", "NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RELACIONIDENTIFICACIÓN
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."RELACIONIDENTIFICACIÓN" ADD CONSTRAINT "RI_ENTIDADDEBIL_FK" FOREIGN KEY ("ED_ESQUEMA_NOMBRE", "ED_TIPODATO_NOMBRE")
	  REFERENCES "INFTEL14_5"."ENTIDADDEBIL" ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE") ENABLE;
 
  ALTER TABLE "INFTEL14_5"."RELACIONIDENTIFICACIÓN" ADD CONSTRAINT "RI_RELACION_FK" FOREIGN KEY ("R_ESQUEMA_NOMBRE", "R_TIPODATO_NOMBRE")
	  REFERENCES "INFTEL14_5"."RELACION" ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SE_RELACIONA
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."SE_RELACIONA" ADD CONSTRAINT "FK_ASS_11" FOREIGN KEY ("E_ESQUEMA_NOMBRE", "E_TIPODATO_NOMBRE")
	  REFERENCES "INFTEL14_5"."ENTIDAD" ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE") ENABLE;
 
  ALTER TABLE "INFTEL14_5"."SE_RELACIONA" ADD CONSTRAINT "FK_ASS_12" FOREIGN KEY ("R_ESQUEMA_NOMBRE", "R_TIPODATO_NOMBRE")
	  REFERENCES "INFTEL14_5"."RELACION" ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBCLASE_CAT
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."SUBCLASE_CAT" ADD CONSTRAINT "FK_ASS_10" FOREIGN KEY ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE")
	  REFERENCES "INFTEL14_5"."ENTIDAD" ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE") ENABLE;
 
  ALTER TABLE "INFTEL14_5"."SUBCLASE_CAT" ADD CONSTRAINT "FK_ASS_9" FOREIGN KEY ("CATEGORIA_NOMBRE")
	  REFERENCES "INFTEL14_5"."CATEGORIA" ("NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBCLASE_ESP
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."SUBCLASE_ESP" ADD CONSTRAINT "FK_ASS_3" FOREIGN KEY ("ESPECIALIZACION_NOMBRE")
	  REFERENCES "INFTEL14_5"."ESPECIALIZACION" ("NOMBRE") ENABLE;
 
  ALTER TABLE "INFTEL14_5"."SUBCLASE_ESP" ADD CONSTRAINT "FK_ASS_4" FOREIGN KEY ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE")
	  REFERENCES "INFTEL14_5"."ENTIDAD" ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUPERCLASE_CAT
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."SUPERCLASE_CAT" ADD CONSTRAINT "FK_ASS_7" FOREIGN KEY ("CATEGORIA_NOMBRE")
	  REFERENCES "INFTEL14_5"."CATEGORIA" ("NOMBRE") ENABLE;
 
  ALTER TABLE "INFTEL14_5"."SUPERCLASE_CAT" ADD CONSTRAINT "FK_ASS_8" FOREIGN KEY ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE")
	  REFERENCES "INFTEL14_5"."ENTIDAD" ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUPERCLASE_ESP
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."SUPERCLASE_ESP" ADD CONSTRAINT "FK_ASS_5" FOREIGN KEY ("ESPECIALIZACION_NOMBRE")
	  REFERENCES "INFTEL14_5"."ESPECIALIZACION" ("NOMBRE") ENABLE;
 
  ALTER TABLE "INFTEL14_5"."SUPERCLASE_ESP" ADD CONSTRAINT "FK_ASS_6" FOREIGN KEY ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE")
	  REFERENCES "INFTEL14_5"."ENTIDAD" ("ESQUEMA_NOMBRE", "TIPODATO_NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TIPODATO
--------------------------------------------------------

  ALTER TABLE "INFTEL14_5"."TIPODATO" ADD CONSTRAINT "TIPODATO_ESQUEMA_FK" FOREIGN KEY ("ESQUEMA_NOMBRE")
	  REFERENCES "INFTEL14_5"."ESQUEMA" ("NOMBRE") ENABLE;
--------------------------------------------------------
--  DDL for Trigger ARC_FKARC_1_ENTIDAD
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "INFTEL14_5"."ARC_FKARC_1_ENTIDAD" BEFORE
  INSERT OR
  UPDATE OF Esquema_Nombre,
    TipoDato_Nombre ON Entidad FOR EACH ROW DECLARE d INTEGER;
  BEGIN
    SELECT A.Discriminador
    INTO d
    FROM TipoDato A
    WHERE A.Esquema_Nombre = :new.Esquema_Nombre
    AND A.Nombre           = :new.TipoDato_Nombre ;
    IF (d                 IS NULL OR d <> '0') THEN
      raise_application_error(-20223,'FK Entidad.Entidad_TipoDato_FK in Table Entidad violates Arc constraint on Table TipoDato - only one FK is permitted');
    END IF;
  END;
/
ALTER TRIGGER "INFTEL14_5"."ARC_FKARC_1_ENTIDAD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ARC_FKARC_1_RELACION
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "INFTEL14_5"."ARC_FKARC_1_RELACION" BEFORE
  INSERT OR
  UPDATE OF Esquema_Nombre,
    TipoDato_Nombre ON Relacion FOR EACH ROW DECLARE d INTEGER;
  BEGIN
    SELECT A.Discriminador
    INTO d
    FROM TipoDato A
    WHERE A.Esquema_Nombre = :new.Esquema_Nombre
    AND A.Nombre           = :new.TipoDato_Nombre ;
    IF (d                 IS NULL OR d <> '1') THEN
      raise_application_error(-20223,'FK Relacion.Relacion_TipoDato_FK in Table Relacion violates Arc constraint on Table TipoDato - only one FK is permitted');
    END IF;
  END;
/
ALTER TRIGGER "INFTEL14_5"."ARC_FKARC_1_RELACION" ENABLE;
