/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author inftel15
 */
public class PanelCreacion extends javax.swing.JPanel implements VistaCreacion{

    /**
     * Creates new form PanelCreacion
     */
    public PanelCreacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Selecionar carpetas");
        jButton1.setFocusPainted(false);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 170, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Metadata-Extractor");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/fondo.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public File[] abrirSelectDir(){
        File[] archivos = null;
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleciona las carpetas");
        fileChooser.setMultiSelectionEnabled(true);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            archivos = fileChooser.getSelectedFiles();
        }
        return archivos;
    }
    
    @Override
    public void controlador(ActionListener ctr) {
        
        jButton1.addActionListener(ctr);
        jButton1.setActionCommand(BotonSeleccionarCarpetas);
    }

    @Override
    public void mostrarTerminado(String message) {
        JOptionPane.showMessageDialog(this, message,"Proceso terminado",JOptionPane.INFORMATION_MESSAGE);
    }
}
