package Vista;

import java.awt.event.ActionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Alfredo
 */
public class PanelCrearPase extends javax.swing.JPanel implements VistaCrearPase{

    /**
     * Creates new form PanelCrearPase
     */
    public PanelCrearPase() {
        initComponents();
        limitArea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtprueba = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtcausa = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/1416608974_tick.png"))); // NOI18N
        jButton9.setText("Guardar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 122, -1));

        jButton12.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/1416608998_arrow_rotate_anticlockwise.png"))); // NOI18N
        jButton12.setText("Volver");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 123, -1));

        txtprueba.setColumns(20);
        txtprueba.setRows(2);
        jScrollPane1.setViewportView(txtprueba);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 514, 59));

        txtcausa.setColumns(20);
        txtcausa.setRows(2);
        jScrollPane2.setViewportView(txtcausa);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 514, 58));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("Pase de Servicio");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel10.setText("Texto");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        jLabel9.setText("Paciente :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        jLabel5.setText("Prueba :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel6.setText("Causa :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/health.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 44, 45));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/rsz_1dna-blue-glass.jpg"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtcausa;
    private javax.swing.JTextArea txtprueba;
    // End of variables declaration//GEN-END:variables

    @Override
     public void controlador(ActionListener ctr) {
        
        jButton9.addActionListener(ctr);
        jButton9.setActionCommand(BotonGuardarPase);
        
        jButton12.addActionListener(ctr);
        jButton12.setActionCommand(BotonVolver);
       
 
    }
      public final void limitArea (){
        txtprueba.setWrapStyleWord(true);
        txtprueba.setLineWrap(true);
        
        txtcausa.setWrapStyleWord(true);
        txtcausa.setLineWrap(true);
                
    }
     public String getPrueba() {
        return txtprueba.getText();
    }
     public String getCausa() {
        return txtcausa.getText();
    }
      public void cambiarLabel(String s) {
        jLabel10.setText(s);
    }
}
