/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import static Vista.VistaReceta.BotonCrearReceta;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author loubna
 */
public  class  PanelReceta extends javax.swing.JPanel implements VistaReceta {

    /**
     * Creates new form PanelReceta
     */
    public PanelReceta() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     
    // <editor-fold defaultstate="collapsed" desc="Generated Code"> 
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RecCrear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MostrarReceta = new javax.swing.JButton();
        jImpremir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jCampo1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jCampo2 = new javax.swing.JTextArea();
        volverAtras = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RecCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/1416608988_page_white_edit.png"))); // NOI18N
        RecCrear.setText("Crear recetas");
        add(RecCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " Medicamento", " Indicaciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 570, 138));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Medicamento");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 216, 90, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Indicaciones");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 216, 90, -1));

        MostrarReceta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/1416618980_table_tab_search.png"))); // NOI18N
        MostrarReceta.setText("Ver receta");
        add(MostrarReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 130, 50));

        jImpremir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/1416612663_file_extension_pdf.png"))); // NOI18N
        jImpremir.setText("Imprimir");
        jImpremir.setMaximumSize(new java.awt.Dimension(109, 23));
        jImpremir.setMinimumSize(new java.awt.Dimension(109, 23));
        jImpremir.setPreferredSize(new java.awt.Dimension(109, 23));
        add(jImpremir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 130, 50));

        jCampo1.setColumns(20);
        jCampo1.setRows(5);
        jScrollPane2.setViewportView(jCampo1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 241, 262, -1));

        jCampo2.setColumns(20);
        jCampo2.setRows(5);
        jScrollPane3.setViewportView(jCampo2);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 290, -1));

        volverAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/1416608998_arrow_rotate_anticlockwise.png"))); // NOI18N
        volverAtras.setText("Volver");
        add(volverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 116, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/stethoscope.png"))); // NOI18N
        jLabel3.setText("Recetas");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 11, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/rsz_1dna-blue-glass.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 440));
    }// </editor-fold>//GEN-END:initComponents
  
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MostrarReceta;
    private javax.swing.JButton RecCrear;
    private javax.swing.JTextArea jCampo1;
    private javax.swing.JTextArea jCampo2;
    private javax.swing.JButton jImpremir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton volverAtras;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cargarRecetas(String Indicaciones, Integer Medicamento) {
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{Medicamento, Indicaciones});
    }

    @Override
    public String getIdIndecacionesOfSelectedRow() {
         int row = jTable1.getSelectedRow();
        if (row == -1) {
            return null;
        } else {
           
            return (String) jTable1.getModel().getValueAt(row, 0);
            
        }
    }

    @Override
    public String getIdIMedicamentoOfSelectedRow() {
           int row = jTable1.getSelectedRow();
        if (row == -1) {
            return null;
        } else {
            
            return (String) jTable1.getModel().getValueAt(row, 1);
        }
    }

    
    @Override
    public void mostrarMensaje1(String mensaje1) {
          jCampo2.setText(mensaje1 + "\n");
    }

   
    @Override
    public void mostrarMensaje2(String mensaje2) {
       jCampo1.setText(mensaje2 + "\n");
    }

    @Override
    public String recogerIndecaciones() {
        String Indicaciones =  jCampo2.getText();
         return Indicaciones;
    }

    @Override
    public String recogerMedicamento() {
        String Medicamento =  jCampo1.getText();
         return Medicamento;
    }
    
   //cargar las recetas en la tabla
    @Override
    public void insertarFila(String a,String b){
        DefaultTableModel datos=(DefaultTableModel) jTable1.getModel();
        datos.addRow(new Object[]{a,b});
     
    }
   
    @Override
    public List<String>  ImpremirCampo() {                                          
        // TODO add your handling code here:
        List<String> recta_array = new ArrayList<>();
        String Indicaciones =  jCampo1.getText();
        String Medicamentos = jCampo2.getText();
        recta_array.add(Indicaciones);
        recta_array.add(Medicamentos);
        return( recta_array);
    }
   
    @Override
    public void controlador(ActionListener ctr) {
        RecCrear.addActionListener(ctr);
        RecCrear.setActionCommand(BotonCrearReceta);
        MostrarReceta.addActionListener(ctr);
        MostrarReceta.setActionCommand(BotonMostrarReceta);
        jImpremir.addActionListener(ctr);
        jImpremir.setActionCommand(GenerarPDF);
        volverAtras.addActionListener(ctr);
        volverAtras.setActionCommand(BotonVolverAtras);
    }

   
                         
}