/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samu
 */
public class PanelPedirCita extends javax.swing.JPanel implements VistaPedirCita {

    /**
     * Creates new form PanelPedirCita
     */
    public PanelPedirCita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hora", "Disponibilidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 149, 260, 240));

        jComboBox1.setName(""); // NOI18N
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 394, -1));

        jLabel1.setText("Seleccionar fecha:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 110, -1, -1));

        jLabel2.setText("Seleccionar especialidad:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 24, -1, -1));

        jLabel3.setText("Seleccionar medico:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 61, -1, -1));

        jComboBox2.setName(""); // NOI18N
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 57, 426, -1));

        jButton1.setText("Buscar citas");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 102, -1, -1));

        jButton2.setText("Aceptar cita");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 219, -1, 100));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 102, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/rsz_1dna-blue-glass.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void controlador(ActionListener ctr) {
        jButton1.addActionListener(ctr);
        jButton1.setActionCommand(BotonVerCitas);
        jButton2.addActionListener(ctr);
        jButton2.setActionCommand(BotonAceptarCita);
        jComboBox1.addActionListener(ctr);
        jComboBox1.setActionCommand(ListaEspecialidades);
    }
    
    @Override
    public int getSelectedRow(){
        return jTable1.getSelectedRow();
    }
    
    @Override
    public void rellenarEspecialidades(String especialidad){
        jComboBox1.addItem(especialidad);
    }
    
    @Override
    public void vaciarMedicos(){
        jComboBox2.removeAllItems();
    }
    
    
    @Override
    public String getEspecialidad() {
        return jComboBox1.getSelectedItem().toString();
    }

    @Override
    public int getMedico() {
        return jComboBox2.getSelectedIndex();
    }
    
    @Override
    public void rellenarMedicos(String nombreMedico) {
        jComboBox2.addItem(nombreMedico);
    }

    @Override
    public Date getFecha() {
        return jDateChooser1.getDate();
    }

    @Override
    public void insertarFila(String hora, boolean disponibilidad) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (disponibilidad)
            model.addRow(new Object[]{hora, "Libre"});
        else
            model.addRow(new Object[]{hora, "Ocupado"});
    }

    @Override
    public String getHoraSeleccionada() {
        int row = jTable1.getSelectedRow();
        return jTable1.getModel().getValueAt(row, 0).toString();
    }
    
    @Override
    public String getDisponibilidadSeleccionada() {
        int row = jTable1.getSelectedRow();
        return jTable1.getModel().getValueAt(row, 1).toString();
    }
    
    @Override
    public void cerrarDialog(){
        JDialog parentFrame = (JDialog)this.getRootPane().getParent();
        parentFrame.dispose();
    }

    @Override
    public void borrarTabla() {
        ((DefaultTableModel)jTable1.getModel()).setRowCount(0);
    }
    
    @Override
    public void mensajeError(String message){
        JDialog parentFrame = (JDialog)this.getRootPane().getParent();
        JOptionPane.showMessageDialog(parentFrame, message,"Error",JOptionPane.ERROR_MESSAGE);
    }   
}
