/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionListener;
import java.util.ResourceBundle;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author inftel15
 */
public class PanelLogin extends javax.swing.JPanel implements VistaLogin{
    
    ResourceBundle myBundle = ResourceBundle.getBundle("Vista/internationalization_en_US");
    
    /**
     * Creates new form PanelLogin
     */
    public PanelLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtusuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        esp = new javax.swing.JButton();
        usa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Login");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 110, 40));

        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 269, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Usuario :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });
        add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 268, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/logo.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        esp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/flag_spain.png"))); // NOI18N
        esp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 2));
        esp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espActionPerformed(evt);
            }
        });
        add(esp, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 50, 40));

        usa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/flag_usa.png"))); // NOI18N
        usa.setBorderPainted(false);
        usa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usaActionPerformed(evt);
            }
        });
        add(usa, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 50, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/rsz_1dna-blue-glass.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaActionPerformed

    private void espActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("Usuario :");
        jLabel2.setText("Contraseña :");
        
        esp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, false));
        esp.setBorderPainted(true);
        usa.setBorderPainted(false);
    }//GEN-LAST:event_espActionPerformed

    private void usaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usaActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("User :");
        jLabel2.setText("Password :");
        
        esp.setBorderPainted(false);
        usa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, false));
        usa.setBorderPainted(true);

    }//GEN-LAST:event_usaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton esp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtusuario;
    private javax.swing.JButton usa;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getUsuario() {
        return txtusuario.getText();
    }
    
    @Override
    public JFrame getPadre(){
        return (JFrame) SwingUtilities.getWindowAncestor(this);
    }

    @Override
    public String getContrasenia() {
        return txtContrasena.getText();
    }

    @Override
    public void controlador(ActionListener ctr) {
        jButton1.addActionListener(ctr);
        jButton1.setActionCommand(BotonLoguearse);
        
        esp.addActionListener(ctr);
        esp.setActionCommand(Esp);
        
        usa.addActionListener(ctr);
        usa.setActionCommand(Usa);
    }
    
    @Override
    public void mError(String e){
        JFrame parentFrame = (JFrame) this.getRootPane().getParent();
        JOptionPane.showMessageDialog(parentFrame, e ,"Error",JOptionPane.ERROR_MESSAGE);
    }
    
    public void limpiar(){
        txtContrasena.setText("");
        txtusuario.setText("");
    }
}
