/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorRecetaCrear;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author loubna
 */
public class PanelRecetaCrear extends javax.swing.JPanel implements VistaRecetaCrear {

    /**
     * Creates new form PanelRecetaCrear
     */
    public PanelRecetaCrear() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CrearReceta = new javax.swing.JButton();
        Atras = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "                             Medicamento", "                            Indicaciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 65, 520, 240));

        CrearReceta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/1416608974_tick.png"))); // NOI18N
        CrearReceta.setText("Crear receta");
        add(CrearReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 320, 150, 48));

        Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/1416608998_arrow_rotate_anticlockwise.png"))); // NOI18N
        Atras.setText("Volver");
        add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 140, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/stethoscope.png"))); // NOI18N
        jLabel3.setText("Recetas");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/rsz_1dna-blue-glass.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 440));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton CrearReceta;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public List<String> recogerDatos() {
        // TODO add your handling code here:

        List<String> datos = new ArrayList<>();

        for (int i = 0; i < jTable1.getRowCount(); i++) {

            String dato = (String) jTable1.getModel().getValueAt(i, 0);
            String dato2 = (String) jTable1.getModel().getValueAt(i, 1);

            datos.add(dato);
            datos.add(dato2);
        }
        System.out.println(datos.get(0));
        System.out.println(datos.get(1));
        
        return (datos);
    }

    @Override
    public void controlador(ActionListener ctr) {
        CrearReceta.addActionListener(ctr);
        CrearReceta.setActionCommand(BotonCrearRecetaBD);
         Atras.addActionListener(ctr);
        Atras.setActionCommand(BotonVolverAtras);
        
    }
}
