/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import consultamedica.ConsultaMedica;
import java.awt.event.ActionListener;
import java.util.ResourceBundle;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samu
 */
public class PanelMedico extends javax.swing.JPanel implements VistaMedico {
    
    public static ResourceBundle myBundle;

    /**
     * Creates new form PanelMedico
     */
    public PanelMedico() {
        
        myBundle = ConsultaMedica.getBundle();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        labelNombre = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        labelEspecialidad = new javax.swing.JLabel();
        especialidad = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        cerrarSesion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                myBundle.getString("PanelMedico.hora"), myBundle.getString("PanelMedico.paciente")
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable2.getTableHeader().setResizingAllowed(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 541, 176));

        jButton1.setText(myBundle.getString("PanelMedico.cita"));
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 140, 40));

        labelNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNombre.setText(myBundle.getString("PanelMedico.nombre"));
        add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 83, 31));

        nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombre.setText("Nombre: ");
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, 31));

        labelEspecialidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEspecialidad.setText(myBundle.getString("PanelMedico.esp"));
        add(labelEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, 31));

        especialidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        especialidad.setText("Nombre: ");
        add(especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, 31));

        error.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        error.setForeground(new java.awt.Color(255, 0, 51));
        add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        cerrarSesion.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/door_in.png"))); // NOI18N
        cerrarSesion.setText(myBundle.getString("PanelMedico.cerrar"));
        add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 151, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/rsz_1dna-blue-glass.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 440));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JLabel error;
    private javax.swing.JLabel especialidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelEspecialidad;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables

    //Solo para la prueba, la fución debe ser como la comentada en la interfaz
    @Override
    public void insertarCita(String hora, String nombrePaciente) {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.addRow(new Object[]{hora, nombrePaciente});
    }
    
    @Override
    public int getSelectedRow(){
        return jTable2.getSelectedRow();
    }
    
    @Override
    public void cargarInfoMedico(String nombre, String apellidos, String especialidad) {
        this.nombre.setText(nombre + " " + apellidos);
        this.especialidad.setText(especialidad);
    }
    
    @Override
    public void mostrarError(String error) {
        this.error.setText(error);
    }
    
    @Override
    public JFrame getPadre() {
        return (JFrame)this.getRootPane().getParent();
    }
    
    @Override
    public void ocultarBoton(){
        jButton1.setVisible(false);
    }

    @Override
    public void controlador(ActionListener ctr) {
        jButton1.addActionListener(ctr);
        jButton1.setActionCommand(BotonIrACita);
        cerrarSesion.addActionListener(ctr);
        cerrarSesion.setActionCommand(BotonCerrarSesion);
    }
}
