/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.DAO.InformeDAO;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author inftel15
 */
public class PanelInformeCrear extends javax.swing.JPanel implements VistaInformeCrear {
    
    /*Integer idpac = 1;
    Integer idpers = 3;*/
    File archivoAdjunto;

    /**
     * Creates new form PanelInforme2
     */
    public PanelInformeCrear() {
        initComponents(); 
        limitArea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        infDiagnostico = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        infTratamiento = new javax.swing.JTextArea();
        infCrear = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        infDatos = new javax.swing.JTextArea();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Informe");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel4.setText("Tratamiento :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 140, -1, -1));

        infDiagnostico.setColumns(1);
        infDiagnostico.setRows(2);
        jScrollPane3.setViewportView(infDiagnostico);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 84, 430, 50));

        jLabel5.setText("Diagnóstico :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 62, -1, -1));

        jLabel6.setText("Datos de Exploración :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 218, -1, -1));

        jLabel2.setText("Paciente : ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 26, -1, 24));

        jLabel3.setText("Texto");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 30, 172, -1));

        infTratamiento.setColumns(1);
        infTratamiento.setRows(2);
        jScrollPane2.setViewportView(infTratamiento);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 162, 432, 50));

        infCrear.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        infCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/1416608974_tick.png"))); // NOI18N
        infCrear.setText("Crear Informe");
        infCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infCrearActionPerformed(evt);
            }
        });
        add(infCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, 42));

        jButton3.setText("Examinar...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 110, 30));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/1416608998_arrow_rotate_anticlockwise.png"))); // NOI18N
        jButton1.setText("  Volver");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 140, 40));

        jCheckBox1.setText("Generar Pdf");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        infDatos.setColumns(1);
        infDatos.setRows(2);
        jScrollPane5.setViewportView(infDatos);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 246, 432, 50));

        jCheckBox2.setText("Enviar Email");
        jCheckBox2.setEnabled(false);
        add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        jLabel7.setText("Sin Archivo");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 327, 110, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/file_extension_pdf16.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 22, 23));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/report_user.png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 44, 45));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/rsz_1dna-blue-glass.jpg"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void infCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infCrearActionPerformed

    }//GEN-LAST:event_infCrearActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            archivoAdjunto = fileChooser.getSelectedFile();
            jLabel3.setText(archivoAdjunto.getName());
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected())
        {
            jCheckBox2.setEnabled(true);
        } else  {
            jCheckBox2.setEnabled(false);
        }
        jCheckBox2.setSelected(false);
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed
    
    public void controlador(ActionListener ctr) {
        jButton1.addActionListener(ctr);
        jButton1.setActionCommand(BotonInformeVolver);
        
        infCrear.addActionListener(ctr);
        infCrear.setActionCommand(BotonInformeCrear);
        
    }
    
    public final void limitArea (){
        infDiagnostico.setWrapStyleWord(true);
        infDiagnostico.setLineWrap(true);
        
        infTratamiento.setWrapStyleWord(true);
        infTratamiento.setLineWrap(true);
        
        infDatos.setWrapStyleWord(true);
        infDatos.setLineWrap(true);
        
    }
    
    @Override
    public void cambiarLabel(String s) {
        jLabel3.setText(s);
    }
    
    @Override
    public String infDiagnostico() {
        String diag = infDiagnostico.getText();
        return diag;
    }
    
    @Override
    public String infTratamiento(){
        String trat = infTratamiento.getText();
        return trat;
    }
    
    @Override
    public String infDatos(){
        String dat = infDatos.getText();
        return dat;
    }
    
    @Override
    public File getAdjunto(){
        File file = archivoAdjunto;
        return file;
    }
    
    @Override
    public boolean checkPDF(){
        return jCheckBox1.isSelected();
    }
    
    @Override
    public boolean checkEmail(){
        return jCheckBox2.isSelected();
    }
    
    public void mError(String e){
        JFrame parentFrame = (JFrame) this.getRootPane().getParent();
        JOptionPane.showMessageDialog(parentFrame, e ,"Error",JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton infCrear;
    private javax.swing.JTextArea infDatos;
    private javax.swing.JTextArea infDiagnostico;
    private javax.swing.JTextArea infTratamiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
