/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import static Vista.PanelMedico.myBundle;
import consultamedica.ConsultaMedica;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author inftel15
 */
public class PanelAdmin extends javax.swing.JPanel implements VistaAdmin {

    /**
     * Creates new form PanelAdmin
     */
    public PanelAdmin() {
        
        myBundle = ConsultaMedica.getBundle();
        
        initComponents();
        labelUsuarioEditar.setVisible(false);
        txtUsuarioEdit.setVisible(false);
        jButtonAceptarEditar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCrearUsuario = new javax.swing.JButton();
        jButtonEditarUsuario = new javax.swing.JButton();
        SubPanerlEditar = new javax.swing.JPanel();
        labelUsuarioEditar = new javax.swing.JLabel();
        txtUsuarioEdit = new javax.swing.JTextField();
        jButtonAceptarEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cerrarSesion = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCrearUsuario.setText(myBundle.getString("PanelAdmin.cUser"));
        add(jButtonCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jButtonEditarUsuario.setText(myBundle.getString("PanelAdmin.eUser"));
        jButtonEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarUsuarioActionPerformed(evt);
            }
        });
        add(jButtonEditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        SubPanerlEditar.setBackground(new java.awt.Color(255, 255, 255));

        labelUsuarioEditar.setText(myBundle.getString("PanelAdmin.nifUser"));

        jButtonAceptarEditar.setText(myBundle.getString("PanelAdmin.Aceptar"));

        javax.swing.GroupLayout SubPanerlEditarLayout = new javax.swing.GroupLayout(SubPanerlEditar);
        SubPanerlEditar.setLayout(SubPanerlEditarLayout);
        SubPanerlEditarLayout.setHorizontalGroup(
            SubPanerlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubPanerlEditarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(SubPanerlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAceptarEditar)
                    .addGroup(SubPanerlEditarLayout.createSequentialGroup()
                        .addComponent(labelUsuarioEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuarioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        SubPanerlEditarLayout.setVerticalGroup(
            SubPanerlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubPanerlEditarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(SubPanerlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuarioEditar)
                    .addComponent(txtUsuarioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAceptarEditar)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        add(SubPanerlEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 290, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/logo.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setText(myBundle.getString("PanelAdmin.pAdmin"));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        cerrarSesion.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/door_in.png"))); // NOI18N
        cerrarSesion.setText(myBundle.getString("PanelAdmin.Logout"));
        add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 151, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarUsuarioActionPerformed
        labelUsuarioEditar.setVisible(true);
        txtUsuarioEdit.setVisible(true);
        jButtonAceptarEditar.setVisible(true);
    }//GEN-LAST:event_jButtonEditarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SubPanerlEditar;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JButton jButtonAceptarEditar;
    private javax.swing.JButton jButtonCrearUsuario;
    private javax.swing.JButton jButtonEditarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelUsuarioEditar;
    private javax.swing.JTextField txtUsuarioEdit;
    // End of variables declaration//GEN-END:variables

    @Override
    public void controlador(ActionListener ctr) {
        jButtonAceptarEditar.addActionListener(ctr);
        jButtonAceptarEditar.setActionCommand(BotonEditarUsuario);
        jButtonCrearUsuario.addActionListener(ctr);
        jButtonCrearUsuario.setActionCommand(BotonCrearUsuario);
        cerrarSesion.addActionListener(ctr);
        cerrarSesion.setActionCommand(BotonCerrarSesion);
    }

    @Override
    public String gettxtNif() {
        return txtUsuarioEdit.getText();
    }

    @Override
    public void mensajeError(String message) {
        JFrame parentFrame = (JFrame)this.getRootPane().getParent();
        JOptionPane.showMessageDialog(parentFrame, message,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
