/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import consultamedica.ConsultaMedica;
import java.awt.event.ActionListener;
import java.util.ResourceBundle;

/**
 *
 * @author inftel15
 */
public class PanelInfoPaciente extends javax.swing.JPanel implements VistaInfoPaciente {
    

    /**
     * Creates new form PanelInfoPaciente
     */
    public PanelInfoPaciente() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        labelNombreMedico = new javax.swing.JLabel();
        nombreMedico = new javax.swing.JLabel();
        labelEspecialidad = new javax.swing.JLabel();
        especialidadMedico = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelNombre1 = new javax.swing.JLabel();
        labelNombrePaciente = new javax.swing.JLabel();
        nombrePaciente = new javax.swing.JLabel();
        labelEspecialidad1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        especialidad1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/health.png"))); // NOI18N
        jButton1.setText("  Pases de Servicio");
        jButton1.setPreferredSize(new java.awt.Dimension(150, 100));
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 191, 75));

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/stethoscope.png"))); // NOI18N
        jButton2.setText("  Recetas");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 176, 75));

        jButton3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/report_user.png"))); // NOI18N
        jButton3.setText("  Informes");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 180, 75));

        labelNombreMedico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNombreMedico.setText("Nombre: ");
        add(labelNombreMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 83, 31));

        nombreMedico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreMedico.setText("Nombre");
        nombreMedico.setToolTipText("");
        add(nombreMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, 31));

        labelEspecialidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEspecialidad.setText("Especialidad: ");
        add(labelEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, 31));

        especialidadMedico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        especialidadMedico.setText("Nombre");
        add(especialidadMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, 31));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 101, 520, 10));

        labelNombre1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNombre1.setText("PACIENTE");
        add(labelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, 31));

        labelNombrePaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNombrePaciente.setText("Nombre : ");
        add(labelNombrePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 83, 31));

        nombrePaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombrePaciente.setText("Nombre");
        add(nombrePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, 31));

        labelEspecialidad1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEspecialidad1.setText("Operaciones :");
        add(labelEspecialidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, 31));

        jLabel2.setText("-");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 228, -1, -1));

        especialidad1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        especialidad1.setText("Alergias :");
        add(especialidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 222, -1, 31));

        jLabel3.setText("-");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/White-Background.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 510, 170));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/rsz_1dna-blue-glass.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 440));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel especialidad1;
    private javax.swing.JLabel especialidadMedico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelEspecialidad;
    private javax.swing.JLabel labelEspecialidad1;
    private javax.swing.JLabel labelNombre1;
    private javax.swing.JLabel labelNombreMedico;
    private javax.swing.JLabel labelNombrePaciente;
    private javax.swing.JLabel nombreMedico;
    private javax.swing.JLabel nombrePaciente;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void cargarInfoMedico(String nombre, String apellidos, String especialidad){
        
        nombreMedico.setText(nombre + " " + apellidos);
        especialidadMedico.setText(especialidad);
    }
    
    @Override
    public void cargarInfoPaciente(String nombre, String apellidos){
        nombrePaciente.setText(nombre + " " + apellidos);
    }
    
    @Override
    public void controlador(ActionListener ctr) {
        
        jButton1.addActionListener(ctr);
        jButton1.setActionCommand(BotonIrAPases);
        
        jButton2.addActionListener(ctr);
        jButton2.setActionCommand(BotonIrARecetas);
        
        jButton3.addActionListener(ctr);
        jButton3.setActionCommand(BotonIrAInformes);
    }
}
